WITH RECURSIVE D AS
(
  SELECT *, 0 AS DEPTH FROM GRID_REPLICA_RGA WHERE
  	SESSION_ID = :sessionId
	AND REPLICA_ID = :replicaId
	AND RGA_REP = :rgaRep
	AND RGA_SEQ = :rgaSeq
	AND REF_REP = :rgaRep
	AND REF_SEQ = :rgaSeq
  UNION ALL
  SELECT D1.*, D.DEPTH + 1 AS DEPTH FROM D INNER JOIN GRID_REPLICA_RGA D1 ON (
	D.SESSION_ID = D1.SESSION_ID
	AND D.REPLICA_ID = D1.REPLICA_ID
	AND D.RGA_REP = D1.RGA_REP
	AND D.RGA_SEQ = D1.RGA_SEQ
	AND D.NODE_REP = D1.REF_REP
	AND D.NODE_SEQ = D1.REF_SEQ
	)
)
SELECT * FROM D
%s
ORDER BY DEPTH %s LIMIT :limit OFFSET :offset;
