CREATE TABLE IF NOT EXISTS GRID_SNAPSHOT (
  `ID` BIGINT NOT NULL,
  `SESSION_ID` CHAR(36) NOT NULL,
  `CLOCK_TABLE` JSON NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `CREATED_BY` BIGINT NOT NULL,
  `EXPIRES_ON` TIMESTAMP(3),
  `S3_KEY` VARCHAR(700) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  PRIMARY KEY `GRID_SNAPSHOT_ID` (`ID`),
  UNIQUE INDEX `GRID_SNAPSHOT_UNQ` (`SESSION_ID`,`CLOCK_TABLE`),
  CONSTRAINT `GRID_SNAPSHOT_SES_ID_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `GRID_SESSION` (`SESSION_ID`) ON DELETE CASCADE
);